config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/catalogue',        to: 'full_catalogue#catalogue'
  get '/contact',          to: 'messages#new', as: 'new_message'
  post '/contact',         to: 'messages#create', as: 'create_message'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message 
    include ActiveModel::Model
    attr_accessor :name, :email, :content
    validates :content, presence: true
    validates :name,  presence: true, length: { maximum: 50 }
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 245 },
                      format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :detect_device_variant
  
  private
    
  def detect_device_variant
    request.variant = :phone if browser.device.mobile?
  end
end

app/controllers/full_catalogue_controller.rb
class FullCatalogueController < ApplicationController
    def catalogue
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new
        @message = Message.new
    end
    
    def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      flash[:info] = "Thank you for your message!" 
      redirect_to root_path 
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
  #def contact
  #end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns title of page
    def full_title(page_title = '')
        base_title = "Christian O'Rourke"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end

end

app/helpers/full_catalogue_helper.rb
module FullCatalogueHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/full_catalogue/_catalogue.html.erb
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-dark pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-dark next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="links">
    <a href="/assets/headshot.png" data-gallery>
        <img src="/assets/full_catalogue.png" alt="Full Catalogue">
    </a>
    <a href="/assets/suit.png" data-gallery></a>
    <a href="/assets/boathouse.png" data-gallery></a>
    <a href="/assets/moore_runway.jpg" data-gallery></a>
    <a href="/assets/nyfw_runway.png" data-gallery></a>
    <a href="/assets/bof_runway.png" data-gallery></a>
    <a href="/assets/moore_show_close.png" data-gallery></a>
</div>

app/views/full_catalogue/catalogue.html+phone.erb
<% provide(:title, "Catalogue") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<div class="center2">
    <%= render 'catalogue' %>
</div>
</meta>

app/views/full_catalogue/catalogue.html.erb
<% provide(:title, "Full Catalogue") %>

    <%= render 'catalogue' %>    

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer">
    <nav>
        <ul>
            <li><%= link_to "Catalogue", catalogue_path %></li>
            <li><%= link_to "Contact", new_message_url %></li>
        </ul>
    </nav>
    <nav class="nav nav-navbar navbar-left">
        <li>
            <%= render 'layouts/insta_button' %>
        </li>
    </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar" id="fixed">
    <div class="container-fluid">
            <nav class="nav navbar-nav navbar-left">
                <div class="container2">
                    <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Menu <b class="caret"></b>
                            </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Home", root_path %></li>
                          <li><%= link_to "Contact", new_message_url %></li>
                        </ul>
                      </li>
                </div>      
            </nav>
    </div>
</header>

app/views/layouts/_insta_button.html.erb
<style>.ig-b- { display: inline-block; }
.ig-b- img { visibility: hidden; }
.ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
.ig-b-32 { width: 32px; height: 32px; background: url(//badges.instagram.com/static/images/ig-badge-sprite-32.png) no-repeat 0 0; }
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
.ig-b-32 { background-image: url(//badges.instagram.com/static/images/ig-badge-sprite-32@2x.png); background-size: 60px 178px; } }</style>
<a href="https://www.instagram.com/christian.orourke/?ref=badge" class="ig-b- ig-b-32"><img src="//badges.instagram.com/static/images/ig-badge-32.png" alt="Instagram" /></a>

app/views/layouts/_phone_header.html.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<header class="navbar" id="fixed">
    <div class="container-fluid">
            <nav class="nav navbar-nav navbar-left">
                <div class="container2">
                    <br />
                    <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Menu <b class="caret"></b>
                            </a>
                        <ul class="dropdown-menu">
                          <br />
                          <br />
                          <br />
                          <li><%= link_to "Home", root_path %></li>
                          <li><%= link_to "Catalogue", catalogue_path %></li>
                          <li><%= link_to "Contact", new_message_url %></li>
                        </ul>
                      </li>
                </div>      
            </nav>
    </div>
</header>
</meta>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/phone_header' %>
  </head>
    <body>
      <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% #debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/header' %>
  </head>
  <body>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% #debug(params) if Rails.env.development? %>
    </div>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/messages/new.html+phone.erb
<% provide(:title, "Contact") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<div class="row">
  <div class="col-md-6 col-centered">
    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
  </div>
</div>
</meta>

app/views/messages/new.html.erb
<div class="row">
  <div class="col-md-6 col-centered">
    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html+phone.erb
<% provide(:title) %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<div class="center2">
        <%= link_to image_tag("headshot.png", alt: "Catalogue",
                      title: "Catalogue"), catalogue_path %>
</div>
</meta>

app/views/static_pages/home.html.erb
<% provide(:title) %>
<div class="center2">
        <div class="hidden-fade">
    
        <%= link_to image_tag("headshot.png", alt: "Catalogue",
                      title: "Catalogue"), catalogue_path %>
    </div>
</div>